changed fuzz-test according to new workplan

diff --git a/.github/workflows/test_fuzz.yml b/.github/workflows/test_fuzz.yml
--- a/.github/workflows/test_fuzz.yml
+++ b/.github/workflows/test_fuzz.yml
@@ -1,14 +1,18 @@
-name: aws-fuzz-test
+name: new_fuzz
 
 on:
   workflow_dispatch:
-  workflow_call:
 
 jobs:
-  fuzz-build:
+  fuzz:
     runs-on: ubuntu-latest
     container:
       image: ubuntu:18.04
+    strategy:
+      matrix:
+        include:
+          - name: db_fuzzer
+          - name: db_map_fuzzer
 
     steps:
       - uses: actions/checkout@v3
@@ -27,9 +31,8 @@ jobs:
           aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
           aws-region: eu-west-2
 
-      - name: fuzbuild
+      - name: ${{ matrix.name }}
         run: |
-           md5sum --version
            echo 'git clone https://github.com/google/libprotobuf-mutator.git \n
              cd libprotobuf-mutator \n
              git checkout ffd86a32874e5c08a143019aad1aaf0907294c9f \n
@@ -46,165 +49,24 @@ jobs:
              cd $GITHUB_WORKSPACE \n
              COMPILE_WITH_ASAN=1 PORTABLE=1 make -j2 static_lib \n
              cd $GITHUB_WORKSPACE/fuzz \n
-             make db_map_fuzzer \n
-             make db_fuzzer \n
+             make ${{ matrix.name }} \n
              ls -alFh $GITHUB_WORKSPACE/fuzz/ \n
              echo ASAN_OPTIONS=detect_leaks=0 ./db_fuzzer \n' > prepfuz.sh
            chmod +x prepfuz.sh
            bash -xv prepfuz.sh
-           md5sum $GITHUB_WORKSPACE/fuzz/db_fuzzer
-           md5sum $GITHUB_WORKSPACE/fuzz/db_map_fuzzer
+           mkdir -p $GITHUB_WORKSPACE/out/
+           ASAN_OPTIONS=detect_odr_violation=0 $GITHUB_WORKSPACE/fuzz/${{ matrix.name }} 2>&1 | sudo tee $GITHUB_WORKSPACE/out/${{ matrix.name }}.log
+           tail -20 $GITHUB_WORKSPACE/out/${{ matrix.name }} | grep "==AddressSanitizer. Thread limit (4194304 threads) exceeded\. Dying\." || echo "${{ matrix.name }} failed!"
            
-         
-      - name: Copy db_map_fuzzer to S3
+      - name: Copy ${{ matrix.name }} logs to S3
         run: |
-          aws s3 cp $GITHUB_WORKSPACE/fuzz/db_map_fuzzer s3://spdb-github-ci/
-     
-      - name: Copy db_fuzzer to S3
-        run: |
-          aws s3 cp $GITHUB_WORKSPACE/fuzz/db_fuzzer s3://spdb-github-ci/
-         
-#       - name: Upload db_map_fuzzer Artifact
-#         uses: actions/upload-artifact@v3.1.0
-#         with:
-#           name: db_map_fuzzer
-#           path: |
-#              ${{ github.workspace }}/fuzz/db_map_fuzzer
-#           retention-days: 1
-             
-#       - name: Upload db_fuzzer Artifact
-#         uses: actions/upload-artifact@v3.1.0
-#         with:
-#           name: db_fuzzer
-#           path: |
-#              ${{ github.workspace }}/fuzz/db_fuzzer
-#           retention-days: 1
-             
-             
-  db_fuzzer:
-    runs-on: ubuntu-latest
-    container:
-      image: ubuntu:18.04
-    continue-on-error: true
-    needs: [fuzz-build]
-      
-    steps:
-      - uses: actions/checkout@v3
-            
-#       - name: Download a Build Artifact
-#         uses: actions/download-artifact@v3.0.0
-#         with:
-#           name: db_fuzzer
-#           path: ${{ github.workspace }}/fuzz/db_fuzzer
-
-      - name: Pre-build
-        run: |
-          apt update && apt install -y libtool sudo gettext pkg-config libsnappy-dev libzstd-dev liblz4-dev binutils m4 unzip ucommon-utils
-          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
-          unzip awscliv2.zip
-          sudo ./aws/install
-          mkdir -p $GITHUB_WORKSPACE/out
-          
-      - name: Configure AWS credentials from Test account
-        uses: aws-actions/configure-aws-credentials@v1
-        with:
-          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
-          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
-          aws-region: eu-west-2
-          
-      - name: download db_fuzzer from s3
-        run: |
-          if [ ! -d $GITHUB_WORKSPACE/fuzz/ ]; then
-            mkdir -p $GITHUB_WORKSPACE/fuzz/
-          fi
-          aws s3 cp s3://spdb-github-ci/db_fuzzer $GITHUB_WORKSPACE/fuzz/db_fuzzer
-          ls -alFh $GITHUB_WORKSPACE/fuzz
-          md5sum --version
-          md5sum $GITHUB_WORKSPACE/fuzz/db_fuzzer
-
-      - name: dbfuzzer
-        run: |
-          ls -l $GITHUB_WORKSPACE/out
-          ls -alFh $GITHUB_WORKSPACE/fuzz
-          sudo chown -R $USER:$USER "$GITHUB_WORKSPACE"
-          sudo chown $USER:$USER "$GITHUB_WORKSPACE/fuzz/db_fuzzer"
-          chmod 777 $GITHUB_WORKSPACE/fuzz/db_fuzzer
-          whoami
-          ls -alFh $GITHUB_WORKSPACE/fuzz
-          ASAN_OPTIONS=detect_odr_violation=0 $GITHUB_WORKSPACE/fuzz/db_fuzzer 2>&1 | sudo tee $GITHUB_WORKSPACE/out/db_fuzzer.log 
-          ls -l $GITHUB_WORKSPACE/out/
-          
-      - name: Copy logs to s3
-        run: |
-          aws s3 cp $GITHUB_WORKSPACE/out/db_fuzzer.log s3://spdb-github-ci/
-          
-#       - name: Upload a Build Artifact
-#         uses: actions/upload-artifact@v3.1.0
-#         with:
-#           path: ${{ github.workspace }}/out/db_fuzzer.log
-#           retention-days: 1
-
-  db_map_fuzzer:
-    runs-on: ubuntu-latest
-    container:
-      image: ubuntu:18.04
-    continue-on-error: true
-    needs:  [fuzz-build]
+          aws s3 cp $GITHUB_WORKSPACE/out/${{ matrix.name }}.log s3://spdb-github-ci/
     
-    steps:
-      - uses: actions/checkout@v3
-            
-#       - name: Download a Build Artifact
-#         uses: actions/download-artifact@v3.0.0
-#         with:
-#           name: db_map_fuzzer
-#           path: ${{ github.workspace }}/fuzz/db_map_fuzzer
-      
-      - name: Pre-build
-        run: |
-          apt update && apt install -y sudo libtool gettext pkg-config libsnappy-dev libzstd-dev liblz4-dev binutils m4 unzip
-          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
-          unzip awscliv2.zip
-          sudo ./aws/install
-          mkdir -p $GITHUB_WORKSPACE/out/
-          
-      - name: Configure AWS credentials from Test account
-        uses: aws-actions/configure-aws-credentials@v1
-        with:
-          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
-          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
-          aws-region: eu-west-2
-          
-      - name: download db_map_fuzzer from s3
-        run: |
-          if [ ! -d $GITHUB_WORKSPACE/fuzz/ ]; then
-            mkdir -p $GITHUB_WORKSPACE/fuzz/
-          fi
-          aws s3 cp s3://spdb-github-ci/db_map_fuzzer $GITHUB_WORKSPACE/fuzz/db_map_fuzzer
-          ls -alFh $GITHUB_WORKSPACE/fuzz
-          md5sum --version
-          md5sum $GITHUB_WORKSPACE/fuzz/db_map_fuzzer
-
-          
-      - name: dbmapfuzzer
-        run: |
-          ls -l $GITHUB_WORKSPACE/out/
-          sudo chown -R $USER:$USER "$GITHUB_WORKSPACE"
-          sudo chown $USER:$USER "$GITHUB_WORKSPACE/fuzz/db_map_fuzzer"
-          chmod 777 $GITHUB_WORKSPACE/fuzz/db_map_fuzzer
-          whoami
-          ls -alFh $GITHUB_WORKSPACE/fuzz
-          ASAN_OPTIONS=detect_odr_violation=0 $GITHUB_WORKSPACE/fuzz/db_map_fuzzer 2>&1 | tee $GITHUB_WORKSPACE/out/db_map_fuzzer.log 
-      
-      - name: Copy logs to s3
-        run: |
-          aws s3 cp $GITHUB_WORKSPACE/out/db_map_fuzzer.log s3://spdb-github-ci/
-          
   fuzzer_sum:
     runs-on: ubuntu-latest
     container:
       image: ubuntu:18.04
-    needs: [db_map_fuzzer, db_fuzzer]
+    needs: [ fuzz ]
       
     steps:
       - uses: actions/checkout@v3
@@ -235,27 +97,15 @@ jobs:
           aws s3 cp s3://spdb-github-ci/db_map_fuzzer.log $GITHUB_WORKSPACE/out/db_map_fuzzer.log || echo "db_map_fuzzer.log not found"
           ls -alFh $GITHUB_WORKSPACE/out
       
-#       - name: Download a Build Artifact
-#         uses: actions/download-artifact@v3.0.0
-#         with:
-#           path: |
-#             ${{ github.workspace }}/out/db_fuzzer.log
-            
-#       - name: Download a Build Artifact
-#         uses: actions/download-artifact@v3.0.0
-#         with:
-#           path: |
-#             ${{ github.workspace }}/out/db_map_fuzzer.log
-      
       - name: fuzzersum
         run: |
           echo "~~~~ db_map_fuzzer LOGS ~~~~~"
-          tail -20 $GITHUB_WORKSPACE/out/db_map_fuzzer.log | grep "==AddressSanitizer. Thread limit (4194304 threads) exceeded\. Dying\." || echo "skoot"
+          tail -20 $GITHUB_WORKSPACE/out/db_map_fuzzer.log | grep "==AddressSanitizer. Thread limit (4194304 threads) exceeded\. Dying\." || echo "db_map_fuzzer failed!"
           echo "~~~~ db_fuzzer LOGS ~~~~~"
-          tail -20 $GITHUB_WORKSPACE/out/db_fuzzer.log | grep "==AddressSanitizer. Thread limit (4194304 threads) exceeded\. Dying\." || echo "skid"
+          tail -20 $GITHUB_WORKSPACE/out/db_fuzzer.log | grep "==AddressSanitizer. Thread limit (4194304 threads) exceeded\. Dying\." || echo "db_fuzzer failed!"
           
       - name: clear s3 bucket
         run: |
-          mkdir -p $GITHUB_WORKSPACE/down
           aws s3 rm s3://spdb-github-ci/ --recursive --include "*"
+
 
